version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./app/src/main/java/br/com/erudio/config/db.env      
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  docker-to-aws-with-java:
    image: docker-to-aws-with-java
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo    
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network  
networks:
    udemy-network:
        driver: bridge